### ISSUE TITLE
support for a haps format spec that extends the VCF format spec

### ISSUE THREAD

**Issue by aryarm** [gymrek-lab/haptools#33]
upsides
- we could use bcftools instead of implementing our own code

downsides
- a lot of stuff gets pushed into the INFO fields
    - ...including the END position of the haplotype lines, which would otherwise be indexed by tabix in our current format spec
- the INFO fields might differ between the haplotype lines and variant lines
    - we would have to check whether this is possible

**Comment by aryarm** [comment]
ok, I've thought about this a bit more...

Rather than converting the _entire_ `.hap` file into a VCF, I wonder if it would be better to just encode the haplotype (H) lines in the `.hap` file in a new VCF. Compared to the `.hap` file, the new VCF would have more information:
1. complete REF and ALT alleles
2. haplotype GTs for each sample
we can include anything else from the `.hap` file as INFO


To be clear, this would exclude the variants from the genotypes VCF, since those are already in a separate file. If someone wanted to create one file containing both the genotypes and the haplotypes, then they could just use `bcftools concat` on the two VCFs.

If someone wants to quickly query the variants in a haplotype, they could just refer to the `.hap` file. So every haplotype VCF would need to be paired with a `.hap` file. In any case, querying the `.hap` file for this info is gonna be much faster than querying a VCF that has a mix of haplotypes and variants.

thoughts, @s041629 ?

**Comment by s041629** [comment]
this is more or less what I have done before to encode HLA types into VCF and run QTLs/GWAS. It is very easy to have each haplotype as one line in the VCF and use the standard genotypes. Here is an example:

##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the haplotype">
##INFO=<ID=COORD,Number=1,Type=String,Description="Haplotype coordinates">
##INFO=<ID=DIGIT,Number=1,Type=Integer,Description="Haplotype digit">
##INFO=<ID=AF,Number=1,Type=Float,Description="Haplotype frequency in the 1000 Genomes">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GN,Number=1,Type=String,Description="Genotype (numeric): 0 = homozygous reference; 0.5 = heterozygous; 1 = homozygous alternative">
....
chr21   14338286        chr21.q.1*1     chr21.q.1       chr21.q.1*1     1       PASS    END=14342857;COORD=21:14338286-14342857;DIGIT=1;AF=0.1721  GT:GN   0|0:0   0|0:0   0|0:0   0|0:0   1|0:0.5 0|0:0   0|0:0   0|0:0   0|0:0   0|0:0   0|0:0   0|0:0   0|0:0   0|0:0   0|0:0   0|0:0      0|0:0   1|0:0.5 

Sorry, I realized that the example VCF that I uploaded here was wrong (it just has SNPs, not haplotypes). I will fix it tomorrow

**Comment by aryarm** [comment]
> It is very easy to have each haplotype as one line in the VCF and use the standard genotypes

Yes, exactly! I think this is probably the most-straightforward way to do it, and it'll make it easy for us to use those haplotypes as input to other tools like PLINK or SuSiE. And yes, I think we should make the ID field of each haplotype match the one in the `.hap` file.

> chr21 14338286 chr21.q.11 chr21.q.1 chr21.q.11 1 PASS END=14342857;COORD=21:14338286-14342857;DIGIT=1;AF=0.1721 GT:GN 0|0:0 0|0:0 0|0:0 0|0:0 1|0:0.5 0|0:0 0|0:0 0|0:0 0|0:0 0|0:0 0|0:0 0|0:0 0|0:0 0|0:0 0|0:0 0|0:0 0|0:0 1|0:0.5

In this example, you're using the IDs in the REF and ALT alleles, right?

**Comment by aryarm** [comment]
Ok, yeah. So just to be clear, what do you use for REF and ALT? I think one complications is that most tools will parse the length of the REF or ALT alleles to figure out how big the variant is. So we may want to use the full length of the haplotype block? Or, alternatively, we may be able to look at how structural variants are encoded and try to adapt something from that.

**Comment by s041629** [comment]
I ended up setting everything to `REF == "A"` and `ALT == "T"`, and never used those field: what I usually do is run `bcftools query` to extract ID and genotypes. But agree with you: using what is normally used for SVs would be the best solution, unless we can define the non-canonical REF and ALT in the VCF header

**Comment by aryarm** [comment]
closing, since this was preliminarily resolved in #45

**Comment by aryarm** [comment]
I might try to see if we encode the REF and ALT alleles as SVs
Or see if there are any other options
But that's a challenge for a different time
