### ISSUE TITLE
try cases where `.hap` file does not follow format exactly

### ISSUE THREAD

**Issue by aryarm** [gymrek-lab/haptools#51]
The `.hap` file format is described in our documentation [here](https://haptools.readthedocs.io/en/latest/formats/haplotypes.html)

The `data.haplotypes.Haplotypes` class is responsible for reading and writing `.hap` files. We have test cases to ensure the class works properly

But what does our code do in situations where the `.hap` file isn't formatted properly and doesn't follow the specification? Can we give helpful error messages?

Here are some things to check:
- [x] what happens when there's an extra field that isn't declared in the header?
    - [x] (related) what happens when there are more extra fields than declared in the header?
- [x] what happens when there are strings in fields where there are supposed to be ints or floats?
- [x] what happens when there's an unsupported line type?

Once we know what happens in each case, we should either
1. ignore the issue in our code but add an error message telling the user to run [the `validate` subcommand](https://github.com/gymrek-lab/haptools/issues/47)
2. raise a ValueError exception that kills the current process
3. just ignore the issue altogether

We should only do item 2 if the issue is especially egregious and will prevent us from continuing. And we should do item 3 if it would be too cumbersome to report the error. But in either case 1 or 2, we could create test cases to ensure these error messages appear.

**Comment by aryarm** [comment]
@ciarareeve , if you choose to do this issue, can you write a small report detailing your findings here within a comment to this issue?

**Comment by ciarareeve** [comment]
In the case that there is any additional field which haptools does not anticipate for a given subcommand then it will produce a KeyError.  IN the case that a string is given when a float or int is required then haptools will throw a ValueError.  Lastly, when there is an unsupported line type (beginning with anything other than an H, V, or #), if it is the first row following the header, then an IndexError is thrown.  If the unsupported line type is any other row, then the unsupported line type is ignored and the output produced is identical to what would be produced if the user had input an expected line type.

**Comment by aryarm** [comment]
looks great, @ciarareeve! thanks for doing all of this

Probably all of these are ok. The user will encounter these errors and then probably just run the `validate` command and get more informative error messages. If anything, the unsupported line type issue is probably the only thing we'll need to fix.

If it's easy to do (and only if it is!), it would be helpful if you could attach stack-traces for each of these Exceptions. Basically, it would be useful to know
1. What is the error message for each exception?
2. Which line of code does the error originate from? (Can you link to it?)

Apologies for not asking for these beforehand. I didn't really realize it would be useful to have them until now.

**Comment by ciarareeve** [comment]
Here is a screen shot if there is an additional field:


![Image](https://user-images.githubusercontent.com/77694019/184007945-577dc980-9bbf-4a50-b62a-136b4975bb1a.png)

This is for a syntax mismatch:


![Image](https://user-images.githubusercontent.com/77694019/184008067-7d19cdaf-cde9-4ca5-b819-6549b200818f.png)

Unsupported line type starting with first row:



![Image](https://user-images.githubusercontent.com/77694019/184008341-0ee91d1a-0917-4367-b232-440189af9ddf.png)

And unsupported line type with any following row ( no error):


![Image](https://user-images.githubusercontent.com/77694019/184008431-a1f22227-afde-492c-9a60-3f020dcf76a0.png)


If you would like this copy&pasted/typed out as more of a report please let me know.

**Comment by aryarm** [comment]
> If you would like this copy&pasted/typed out as more of a report please let me know.
No, this is perfect - it's exactly what I was looking for.

I'll go ahead and use this info to update the TODO for #47
